# Generated by Django 4.1.4 on 2023-01-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="Направление")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127, verbose_name="Отрасль")),
            ],
            options={
                "verbose_name": "Отрасль",
                "verbose_name_plural": "Отрасли",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63, verbose_name="Метод")),
            ],
            options={
                "verbose_name": "Метод",
                "verbose_name_plural": "Методы",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127, verbose_name="Вакансия")),
                ("description", models.TextField(verbose_name="Описание")),
                ("active", models.BooleanField(default=True, verbose_name="Активно")),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ("active", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Проект")),
                ("content", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.industry",
                        verbose_name="Отрасль",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.method",
                        verbose_name="Метод",
                    ),
                ),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты",},
        ),
    ]
