# Generated by Django 4.1.4 on 2023-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Псевдоним"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Переменная"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Значение (для формул)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент сайта",
                "verbose_name_plural": "Контент сайта",
                "ordering": ("alias",),
            },
        ),
        migrations.AlterModelOptions(
            name="cost",
            options={
                "ordering": ("-id",),
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
            },
        ),
        migrations.AlterModelOptions(
            name="costgroup",
            options={
                "ordering": ("-id",),
                "verbose_name": "Группа цен",
                "verbose_name_plural": "Группы цен",
            },
        ),
    ]
