# Generated by Django 4.1.4 on 2023-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="method",),
        migrations.AddField(
            model_name="project",
            name="method",
            field=models.ManyToManyField(related_name="projects", to="main.method"),
        ),
    ]
