# Generated by Django 4.1.4 on 2023-01-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_project_method_project_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название группы"),
                ),
            ],
            options={
                "verbose_name": "Группа цен",
                "verbose_name_plural": "Группы цен",
            },
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название услуги"),
                ),
                ("cost", models.CharField(max_length=63, verbose_name="Стоимость")),
                ("term", models.CharField(max_length=31, verbose_name="Срок")),
                (
                    "costgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.costgroup",
                        verbose_name="Группа услуг",
                    ),
                ),
            ],
            options={"verbose_name": "Цена", "verbose_name_plural": "Цены",},
        ),
    ]
