# Generated by Django 4.1.4 on 2023-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_sitecontent_alter_cost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Содержимое"),
        ),
    ]
