# Generated by Django 4.1.4 on 2023-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_sitecontent_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="value",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Значение (для формул)",
            ),
        ),
    ]
