# Generated by Django 4.1.4 on 2023-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_sitecontent_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="url_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя url-адреса"
            ),
        ),
    ]
