# Generated by Django 4.1.4 on 2023-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_sitecontent_url_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider", name="title", field=models.CharField(max_length=50),
        ),
    ]
