# Generated by Django 4.1.4 on 2023-01-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_cost_cost_alter_cost_term_alter_cost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="costgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="main.costgroup",
                verbose_name="Группа услуг",
            ),
        ),
    ]
