# Generated by Django 4.1.4 on 2023-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_slider_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="search_page",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя для поиска"
            ),
        ),
    ]
