# Generated by Django 4.1.4 on 2023-01-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_cost_costgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="cost",
            field=models.CharField(max_length=200, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="cost",
            name="costgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost",
                related_query_name="costs",
                to="main.costgroup",
                verbose_name="Группа услуг",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="term",
            field=models.CharField(max_length=200, verbose_name="Срок"),
        ),
        migrations.AlterField(
            model_name="cost",
            name="title",
            field=models.CharField(max_length=350, verbose_name="Название услуги"),
        ),
        migrations.AlterField(
            model_name="costgroup",
            name="title",
            field=models.CharField(max_length=350, verbose_name="Название группы"),
        ),
    ]
