# Generated by Django 4.1.4 on 2023-01-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_cost_cost_alter_cost_costgroup_alter_cost_term_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, verbose_name="Имя")),
                ("contact", models.CharField(max_length=63, verbose_name="Контакт")),
                ("text", models.TextField(verbose_name="Сообщение")),
                ("link", models.CharField(max_length=127, verbose_name="Ссылка")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "answered",
                    models.BooleanField(default=False, verbose_name="Просмотрено"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Проект")),
                ("content", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.industry",
                        verbose_name="Отрасль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("created_at",),
            },
        ),
    ]
