# Generated by Django 4.1.4 on 2023-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_feedback_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedback"},
        ),
        migrations.RemoveField(model_name="article", name="industry",),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="industry",
            field=models.ManyToManyField(to="main.industry", verbose_name="Отрасль"),
        ),
    ]
