# Generated by Django 4.1.4 on 2023-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_article_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="direction",),
        migrations.RemoveField(model_name="project", name="industry",),
        migrations.RemoveField(model_name="project", name="method",),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedbacks"},
        ),
        migrations.AlterField(
            model_name="costgroup",
            name="title",
            field=models.CharField(
                max_length=350, unique=True, verbose_name="Название группы"
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="title",
            field=models.CharField(
                max_length=31, unique=True, verbose_name="Направление"
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="title",
            field=models.CharField(max_length=127, unique=True, verbose_name="Отрасль"),
        ),
        migrations.DeleteModel(name="Method",),
        migrations.DeleteModel(name="Project",),
    ]
