# Generated by Django 4.1.4 on 2023-02-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_project_direction_remove_project_industry_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Article", new_name="Project",),
    ]
