# Generated by Django 4.1.4 on 2023-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_article_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
            ],
        ),
    ]
