# Generated by Django 4.1.4 on 2023-02-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_slider"),
    ]

    operations = [
        migrations.DeleteModel(name="FeedBack",),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
